version: "3.5"
services:
  #Deploy a Consumer.
  consumer:
    build: .
    container_name: donor-consumer
    ports:
      - 8104:8080
    image: oawofolu/ssm-donorservice:v1
    depends_on:
      - zookeeper
      - kafka
      - postgres